package org.fernando.setup.TestSuite1;

import io.restassured.response.ValidatableResponse;
import org.fernando.setup.baseRequest.BaseAPI;
import org.junit.jupiter.api.Test;

import static org.hamcrest.Matchers.*;
import static io.restassured.module.jsv.JsonSchemaValidator.*;

import static io.restassured.RestAssured.given;

/**First Tests Class to demonstrate to demonstrate the structure**/
class FirstTest extends BaseAPI {


    /**This first test is intended just to demonstrate the structure of the project**/
    @Test
    void testGetACertainUser_functional(){
        ValidatableResponse response = given()
                .when().get(this.props.loginUrl())
                .then().statusCode(200)
                .and().body("data.first_name", equalTo("Janet"))
                .and().body("data.avatar", notNullValue());
    }

    @Test
    void testGetACertainUser_contract(){
        ValidatableResponse response = given()
                .when().get(this.props.loginUrl())
                .then().statusCode(200)
                .and().body(matchesJsonSchemaInClasspath("schemas/GetUserContract.json"));

        // Json Generated by: https://www.liquid-technologies.com/online-json-to-schema-converter
    }
}
