package TestSuite1;

import io.restassured.response.ValidatableResponse;
import org.junit.Before;
import org.junit.Test;
import utils.Utils;

import static io.restassured.RestAssured.*;
import static io.restassured.matcher.RestAssuredMatchers.*;
import static org.hamcrest.Matchers.*;
import static io.restassured.module.jsv.JsonSchemaValidator.*;

import static io.restassured.RestAssured.given;

/**First Tests Class to demonstrate to demonstrate the structure**/
public class FirstTest extends Utils {

    private final String ENDPOINT = "/users/2";

    /**This first test is intended just to demonstrate the structure of the project**/
    @Test
    public void testGetACertainUser_functional(){
        ValidatableResponse response = given()
                .when().get(host + ENDPOINT)
                .then().statusCode(200)
                .and().body("data.first_name", equalTo("Janet"))
                .and().body("data.avatar", notNullValue());
    }

    @Test
    public void testGetACertainUser_contract(){
        ValidatableResponse response = given()
                .when().get(host + ENDPOINT)
                .then().statusCode(200)
                .and().body(matchesJsonSchemaInClasspath("Contracts/GetUserContract.json"));


        // Json Generated by: https://www.liquid-technologies.com/online-json-to-schema-converter
    }
}
