# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Running Rest Assured Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - name: Download repository
       uses: actions/checkout@v4
     - name: Set up JDK 11
       uses: actions/setup-java@v3
       with:
        java-version: 11
        distribution: 'adopt'
        cache: maven
     - name: Test with Maven
       run: mvn clean test surefire-report:report -Daggregate=true
     - name: Publish Test Report
       uses: scacap/action-surefire-report@v1
       with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
     - name: Archive test results
       uses: actions/upload-artifact@v3
       with:
         name: test-results-report
         path: target/site/surefire-report.html
